mybatis:
  mapper-locations: classpath*:cn/geoair/**/mapper/**/impl/*.xml
  type-aliases-package: com.gtc.**.model.**.entity
  type-handlers-package: cn.geoair.orm.mybatis.handler
  
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
